#build and deploy
steps:
  - name: node
    entrypoint: npm
    args: ['install']
  - name: node
    entrypoint: npm
    args: ['run', 'build']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'eu.gcr.io/badge-260212/material', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'eu.gcr.io/$PROJECT_ID/material']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'material', '--image', 'eu.gcr.io/badge-260212/material:latest', '--region', 'europe-west4', '--platform', 'managed', '--concurrency', '80', '--max-instances', '10', '--memory', '128Mi', '--timeout', '30s', '--allow-unauthenticated', '--async']
    
